### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by isaioliva** [mrdav1111/Taxi24#1]
Hola Angel,

¿en dónde estan los scripts de base de datos?

**Comment by isaioliva** [comment]
Angel mira cargue la base una base de datos, si puedes darnos más detalle de como hacer el restore por favor
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Taxi24.Servicios.Interno.Conductores.ConductoresClient.ObtenerListaConductores(ObtenerListaConductoresRequest request, CallOptions options) in /src/Taxi24.Gateways.REST/obj/Release/net5.0/ConductoresGrpc.cs:line 170
   at Taxi24.Servicios.Interno.Conductores.ConductoresClient.ObtenerListaConductores(ObtenerListaConductoresRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /src/Taxi24.Gateways.REST/obj/Release/net5.0/ConductoresGrpc.cs:line 166
   at Taxi24.Gateways.REST.Controllers.ConductoresController.ObtenerConductores(Int64 empresaId) in /src/Taxi24.Gateways.REST/Controllers/ConductoresController.cs:line 27
   at lambda_method2(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: text/plain
Accept-Encoding: gzip, deflate, br
Accept-Language: es-419,es;q=0.9,en;q=0.8
Cookie: pga4_session=adb23aa0-920e-44d2-8336-409a618abaad!iCGyANZYyNNGqngpg+NhjXVKbCc=; PGADMIN_LANGUAGE=en
Host: localhost:8080
Referer: http://localhost:8080/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty

![image](https://user-images.githubusercontent.com/38478132/117727605-42559000-b1b6-11eb-9ca6-e2eabeb79da3.png)

**Comment by mrdav1111** [comment]
Saludos,

Veo que está ejecutando el script en la base de datos llamada Postgres, los
script deben ejecutarse en la base de datos correspondiente.

Puede abrir un query tool para cada base de datos primero seleccionando la
base de datos y presionando el siguiente botón que está en el círculo rojo.
Para ver o cambiar la base de datos del query tool es en el botón circulo
en verde.

![image](https://user-images.githubusercontent.com/18040506/117730921-31f3e400-b1bb-11eb-8354-070369b92810.jpeg)

**Comment by isaioliva** [comment]
en todos me esta marcando error:
![image](https://user-images.githubusercontent.com/38478132/117734004-86e62900-b1c0-11eb-85c1-ea22d1e25acf.png)

![image](https://user-images.githubusercontent.com/38478132/117734011-8cdc0a00-b1c0-11eb-8d8a-56a7d99f3d4c.png)


![image](https://user-images.githubusercontent.com/38478132/117734017-91a0be00-b1c0-11eb-9aab-c68ef7e57801.png)


![image](https://user-images.githubusercontent.com/38478132/117734021-95ccdb80-b1c0-11eb-94a2-926e0edeb3b5.png)

**Comment by mrdav1111** [comment]
Hola @isaioliva,

Los Scripts han sido actualizados para que sean compatibles con el query tool de pgadmin.

Los nuevos Scripts utilizan el `INSERT INTO` en lugar del `COPY` de los anteriores.

https://github.com/mrdav1111/Taxi24/blob/dabcb18008ef0428df64f5d75dfde1a3cb0e79a8/Database/Taxi24.Pasajeros.sql#L73-L75
https://github.com/mrdav1111/Taxi24/blob/5459e9b652c7da22af28f074900bbcc330cf747e/Database/Taxi24.Pasajeros.sql#L73-L77
